#!/bin/sh -ex

while true
do
  secpkg update secpkg || true
  secpkg update vhcd-testnet
  vhcd-testnet "$@"
  if [ -f .vhcd-testnet-needs-update ]
  then
    rm -f .vhcd-testnet-needs-update
  else
    exit $?
  fi
done
